### ISSUE TITLE
Support to eval sexp at point?

### ISSUE THREAD

**Issue by ahungry** [SerialDev/ijanet-mode#1]
I see region support, but manually selecting a region to eval is quite at-odds with how evaluation works in all the other lisp likes (Emacs itself, CIDER/clojure, Geiser/Scheme etc.).

Would it be possible to have DWIM type support?  (So, if I run an eval sexp - it would eval the code in my current sexp?)

**Comment by SerialDev** [comment]
https://github.com/SerialDev/ijanet-mode/commit/2821db192fd0733d402cbd1c58f6060aa02ef100#diff-8155c76019af85f68de159a3843ca13bR245

This should do the trick, just add a keybinding for ijanet-eval-sexp-at-point

**Comment by ahungry** [comment]
Nice, thank you!
